# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
